name: "Semver"

on:
  push:
    branches:
      - main
  workflow_call:
    outputs:
      new_tag:
        description: "New tag"
        value: ${{ jobs.semver.outputs.new_tag }}
  workflow_dispatch:
    inputs:
      push:
        description: "Push"
        required: false
        type: string
        default: "false"

jobs:
  semver:
    name: "Semver"
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.semver.outputs.new_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history for semver analysis

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: semver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: ${{ github.event_name != 'push' && github.event.inputs.push != 'true' }}
